version: '3.5'
# "postgres://postgres:postgres@localhost:5432"
services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: development_database
